name: Primero bueno

on:
  release:
    types: [published]
    
jobs:
  di_hola:
    runs-on: Linux
    steps:
      - name: Traer el repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: echo
        run: echo "hola $DAY_OF_WEEK"
      - name: listar variables
        run: env
      - name: build
        run: docker build -t goyete:1.0.0 .
