name: Deploy on release

on:
  release:
    types: [published]
    
jobs:
  di_hola:
    runs-on: Linux
    steps:
      - name: Traer el repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: ${{ github.ref_name }}
        run: echo "hola ${{ github.ref_name }}"
      - name: listar variables
        run: env
      - name: build
        run: docker build -t goyete:${{ github.ref_name }} .
